language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=8c3335c688370e0aa8f44a1d671e75996786ab29578a60ade5b476a6312fd145"
install:
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
cache:
  directories:
    - 'node_modules'
